"""HTTP protocol models for the read-only product drawing assistant API.

本模块是协议层：使用严格字段白名单接收请求、验证响应，并在 HTTP 模型和领域
``AssistantRequest``/``AnswerPackage`` 之间转换。领域 DTO（``assistant_models``）
保持框架无关；这里不复制 DrawingAssistantService 的完整业务规则，也不暴露
URI、凭据、Cypher 或底层 driver/session/repository 字段。默认只读，不提供
``write_back`` / ``allow_write_back`` 输入字段。
"""

from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field, StrictBool, field_validator, model_validator

from .assistant_models import AssistantRequest, AssistantScope

ASSISTANT_HTTP_ADAPTER = "drawing-assistant-http"
ASSISTANT_HTTP_CONTRACT_VERSION = "drawing-assistant-http-v1"


class HttpAssistantScopeHint(BaseModel):
    """Business-ID scope hint mirroring :class:`AssistantScope` with length limits."""

    model_config = ConfigDict(extra="forbid")

    project_id: str | None = Field(default=None, min_length=1, max_length=200)
    drawing_set_id: str | None = Field(default=None, min_length=1, max_length=200)
    page_id: str | None = Field(default=None, min_length=1, max_length=200)
    block_id: str | None = Field(default=None, min_length=1, max_length=200)
    element_id: str | None = Field(default=None, min_length=1, max_length=200)
    cross_section_id: str | None = Field(default=None, min_length=1, max_length=200)
    table_id: str | None = Field(default=None, min_length=1, max_length=200)
    table_caption_id: str | None = Field(default=None, min_length=1, max_length=200)
    claim_id: str | None = Field(default=None, min_length=1, max_length=200)

    @field_validator("*")
    @classmethod
    def _not_blank(cls, value: Any) -> Any:
        if isinstance(value, str) and not value.strip():
            raise ValueError("business IDs must not be blank")
        return value

    def to_assistant_scope(self) -> AssistantScope | None:
        """Convert to a domain :class:`AssistantScope`, or ``None`` when empty."""

        values = {
            field_name: getattr(self, field_name)
            for field_name in (
                "project_id",
                "drawing_set_id",
                "page_id",
                "block_id",
                "element_id",
                "cross_section_id",
                "table_id",
                "table_caption_id",
                "claim_id",
            )
        }
        if all(value is None for value in values.values()):
            return None
        return AssistantScope(**values)


class HttpAssistantRequest(BaseModel):
    """Strict request model for ``POST /api/v1/drawing-assistant/ask``."""

    model_config = ConfigDict(extra="forbid")

    request_id: str | None = Field(default=None, min_length=1, max_length=128)
    question: str = Field(min_length=1, max_length=2000)
    language: str = Field(default="zh-CN", min_length=1, max_length=32)
    scope_hint: HttpAssistantScopeHint | None = None
    conversation_context: str | None = Field(default=None, min_length=1, max_length=4000)
    allow_recognition: StrictBool = True
    answer_format: str = Field(default="json_and_text", min_length=1, max_length=32)

    @field_validator("question", "language", "conversation_context", "answer_format")
    @classmethod
    def _not_blank(cls, value: Any) -> Any:
        if isinstance(value, str) and not value.strip():
            raise ValueError("text fields must not be blank")
        return value

    @model_validator(mode="after")
    def _no_write_back_fields(self) -> "HttpAssistantRequest":
        return self

    def to_assistant_request(self, request_id: str) -> AssistantRequest:
        """Convert to a fixed read-only domain :class:`AssistantRequest`."""

        scope = self.scope_hint.to_assistant_scope() if self.scope_hint is not None else None
        return AssistantRequest(
            request_id=request_id,
            question=self.question,
            conversation_context=self.conversation_context,
            scope_hint=scope,
            language=self.language,
            allow_recognition=self.allow_recognition,
            allow_write_back=False,
            answer_format=self.answer_format,
        )


class HttpAssistantMeta(BaseModel):
    """Per-response metadata generated by the server."""

    request_id: str
    adapter: Literal["drawing-assistant-http"] = ASSISTANT_HTTP_ADAPTER
    contract_version: Literal["drawing-assistant-http-v1"] = ASSISTANT_HTTP_CONTRACT_VERSION


class HttpAssistantAnswer(BaseModel):
    """Validated serialized product answer projection without reinterpreting facts."""

    answer_contract_version: str | None = None
    request_id: str
    status: str | None = None
    machine_answer: dict[str, Any] | None = None
    text_answer: str | None = None
    claims: list[dict[str, Any]] = Field(default_factory=list)
    citations: list[dict[str, Any]] = Field(default_factory=list)
    warnings: list[Any] = Field(default_factory=list)
    unsupported_parts: list[str] = Field(default_factory=list)
    recognition_run_ids: list[str] = Field(default_factory=list)


class HttpAssistantSuccessEnvelope(BaseModel):
    """Stable success envelope for product HTTP responses."""

    ok: Literal[True] = True
    data: HttpAssistantAnswer
    meta: HttpAssistantMeta


class HttpAssistantErrorBody(BaseModel):
    """Stable sanitized error body; never carries secrets or stack traces."""

    code: str
    message: str
    retryable: bool


class HttpAssistantErrorEnvelope(BaseModel):
    """Stable failure envelope for product HTTP responses."""

    ok: Literal[False] = False
    error: HttpAssistantErrorBody
    meta: HttpAssistantMeta


class HttpAssistantHealthResponse(BaseModel):
    """Health payload; never claims live Neo4j verification."""

    status: str
    service: str
    contract_version: str
    neo4j_status: str | None = None


def http_answer_from_package(data: dict[str, Any]) -> HttpAssistantAnswer:
    """Validate the serialized answer projection without reinterpreting facts."""

    return HttpAssistantAnswer.model_validate(data)


__all__ = (
    "ASSISTANT_HTTP_ADAPTER",
    "ASSISTANT_HTTP_CONTRACT_VERSION",
    "HttpAssistantAnswer",
    "HttpAssistantErrorBody",
    "HttpAssistantErrorEnvelope",
    "HttpAssistantHealthResponse",
    "HttpAssistantMeta",
    "HttpAssistantRequest",
    "HttpAssistantScopeHint",
    "HttpAssistantSuccessEnvelope",
    "http_answer_from_package",
)
